import React,{useEffect,useState} from 'react'
import {api} from './api.js'
export function EmailVerification({user,onUser}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 if(user.demo)return null
 return <section className="panel"><span className="eyebrow">EMAIL SECURITY</span><h2>{user.email_verified?'Email verified':'Verify your email'}</h2><p className="muted">{user.email_verified?'Your email address has been confirmed.':'Confirm that you own this address. This helps keep your account recoverable.'}</p>{!user.email_verified&&<button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await api('/auth/send-verification','POST');setMessage(r.message)}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'Sending…':'Send verification link'}</button>}{message&&<p role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</section>
}
export function ForgotPassword(){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 return <form onSubmit={async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');setBusy(true);setError('');try{const r=await api('/auth/forgot-password','POST',{email});setMessage(r.message)}catch(e){setError(e.message)}finally{setBusy(false)}}}><p className="muted">Enter your account email. We’ll send a one-time link to choose a new password.</p><label>Email address<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><button className="button primary" disabled={busy}>{busy?'Requesting…':'Send reset link'}</button>{message&&<p role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}</form>
}
export function RecoveryGate({onUser}){
 const [action,setAction]=useState(()=>{const f=new URLSearchParams(location.hash.slice(1));const kind=f.has('reset')?'reset':f.has('verify')?'verify':null;if(!kind)return null;const token=f.get(kind);return {kind,token}})
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{if(action)history.replaceState(null,'',location.pathname+location.search)},[])
 if(!action)return null
 return <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="Account security"><h2>{action.kind==='reset'?'Choose a new password':'Verify your email'}</h2>{message?<><p role="status">{message}</p><button className="button primary" onClick={()=>setAction(null)}>Continue</button></>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');if(action.kind==='reset'&&f.get('password')!==f.get('confirm')){setError('Passwords do not match.');return}setBusy(true);try{const r=await api('/auth/'+(action.kind==='reset'?'reset-password':'verify-email'),'POST',{token:action.token,...(action.kind==='reset'?{new_password:f.get('password')}:{})});setMessage(r.message);setAction({...action,token:''});onUser(await api('/me'))}catch(e){setError(e.message)}finally{setBusy(false)}}}>{action.kind==='reset'?<><label>New password<input name="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label><label>Confirm new password<input name="confirm" type="password" autoComplete="new-password" minLength={10} maxLength={128} required/></label></>:<p>Confirm this email address for your Tradersecho account.</p>}{error&&<p className="error" role="alert">{error}</p>}<div className="button-row"><button className="button primary" disabled={busy}>{busy?'Please wait…':action.kind==='reset'?'Reset password':'Verify email'}</button><button type="button" className="button" disabled={busy} onClick={()=>setAction(null)}>Cancel</button></div></form>}</section></div>
}
