import React from 'react'
import './home.css'

const number=n=>Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n)
function Illustration({kind}){
 return <svg viewBox="0 0 320 150" fill="none" aria-hidden="true" className={'home-illustration art-'+kind}>
  <path d="M0 120H320M0 80H320M0 40H320M40 0V150M100 0V150M160 0V150M220 0V150M280 0V150" stroke="currentColor" opacity=".07"/>
  {kind==='market'?<><path d="M15 128 62 106 94 116 129 72 169 91 211 38 245 51 305 14V150H15Z" fill="currentColor" opacity=".08"/><path d="m15 128 47-22 32 10 35-44 40 19 42-53 34 13 60-37" stroke="currentColor" strokeWidth="3"/><circle cx="211" cy="38" r="13" fill="currentColor" opacity=".13"/><circle cx="211" cy="38" r="4" fill="currentColor"/><path d="m294 14 11 0v11" stroke="currentColor" strokeWidth="2"/></>:null}
  {kind==='briefing'?<><g transform="rotate(-9 160 75)"><rect x="92" y="12" width="135" height="132" rx="8" fill="#182627" stroke="currentColor" opacity=".5"/></g><g transform="rotate(5 160 75)"><rect x="102" y="3" width="132" height="143" rx="8" fill="#1b2928" stroke="currentColor"/><path d="M119 27h42M119 46h93M119 54h66" stroke="currentColor" strokeWidth="3"/><rect x="119" y="72" width="35" height="48" rx="3" fill="currentColor" opacity=".15"/><path d="M168 77h43M168 90h34M168 103h40M168 116h27" stroke="currentColor" opacity=".6"/></g><circle cx="237" cy="114" r="21" fill="#253a30" stroke="currentColor"/><path d="m228 114 6 6 11-13" stroke="currentColor" strokeWidth="2"/></>:null}
  {kind==='watchlist'?<><circle cx="170" cy="78" r="61" stroke="currentColor" opacity=".2"/><circle cx="170" cy="78" r="42" stroke="currentColor" opacity=".3"/><path d="m170 41 11 23 25 4-18 18 4 25-22-12-23 12 5-25-19-18 26-4Z" fill="currentColor" fillOpacity=".12" stroke="currentColor" strokeWidth="2"/><circle cx="109" cy="76" r="5" fill="currentColor"/><circle cx="219" cy="115" r="4" fill="currentColor"/><path d="M56 46h27M69 33v26M253 57h18M262 48v18" stroke="currentColor" opacity=".6"/></>:null}
  {kind==='voices'?<><path d="m73 73 81-24 84 50M73 73l77 44 88-18M154 49l-4 68" stroke="currentColor" opacity=".4"/>{[[73,73,24],[154,49,29],[238,99,25],[150,117,17]].map(([x,y,r])=><g key={x}><circle cx={x} cy={y} r={r} fill="#1b282b" stroke="currentColor"/><circle cx={x} cy={y-5} r={r/4} fill="currentColor" opacity=".7"/><path d={`M${x-r/2} ${y+r/2}q0 -${r/2} ${r/2} -${r/2}t${r/2} ${r/2}`} stroke="currentColor"/></g>)}</>:null}
  {kind==='community'?<><path d="M49 28h149a12 12 0 0 1 12 12v50a12 12 0 0 1-12 12h-85l-28 23v-23H49a12 12 0 0 1-12-12V40a12 12 0 0 1 12-12Z" fill="#1a2b2b" stroke="currentColor"/><path d="M67 54h111M67 70h77" stroke="currentColor" opacity=".7"/><path d="M165 76h96a10 10 0 0 1 10 10v34a10 10 0 0 1-10 10h-17v14l-23-14h-56a10 10 0 0 1-10-10V86a10 10 0 0 1 10-10Z" fill="#243536" stroke="currentColor"/>{[182,212,242].map(x=><circle key={x} cx={x} cy="104" r="4" fill="currentColor"/>)}</>:null}
  {kind==='data'?<><ellipse cx="160" cy="34" rx="72" ry="23" fill="currentColor" fillOpacity=".1" stroke="currentColor"/><path d="M88 34v74c0 31 144 31 144 0V34M88 70c0 31 144 31 144 0" stroke="currentColor"/><path d="M112 61v7M112 97v7" stroke="currentColor" strokeWidth="4"/><circle cx="236" cy="112" r="20" fill="#1e3030" stroke="currentColor"/><path d="m227 112 6 6 12-13" stroke="currentColor" strokeWidth="2"/></>:null}
 </svg>
}
const destinations=[
 ['market','Market pulse','Find the names making noise.','Explore ticker attention, momentum and the posts behind it.','Explore the market'],
 ['briefing','Daily briefing','The day, distilled.','Get the biggest conversations in one considered recap.','Read the briefing'],
 ['watchlist','My watchlist','Keep your conviction close.','A focused view of the stocks you want to follow.','Open your watchlist'],
 ['voices','Tracked voices','Better sources. Clearer thinking.','Read collected takes from curated voices and your own circle.','Follow the conversation'],
 ['community','Trading room','Bring a thesis. Find a perspective.','Exchange ideas, ask better questions and challenge assumptions.','Enter the room'],
 ['data','Data sources','Know what’s behind the numbers.','Explore our coverage, collection history and methodology.','Explore the coverage'],
]
export function Home({user,data,status,watchlist,loading,source,onNavigate,onTicker}){
 const rows=data?.rows||[],leaders=[...rows].sort((a,b)=>b.mentions-a.mentions).slice(0,3)
 const asOf=data?.as_of?new Date(data.as_of*1000):null
 const stale=source==='x'&&asOf&&Date.now()-asOf.getTime()>36*3600000
 return <div className="home-dashboard">
  <section className="home-welcome"><div><span className="eyebrow">YOUR RESEARCH STARTS HERE</span><h1>A little context.<br/><span>A clearer perspective.</span></h1><p>Welcome back, {user.display_name}. Follow the conversation,<br className="home-break"/> find your next question, and make the market your own.</p><button className="button primary" onClick={()=>onNavigate('briefing')}>Catch up with the daily briefing <span aria-hidden="true">↗</span></button></div><div className="home-orbit" aria-hidden="true"><div className="orbit-ring ring-two"/><div className="orbit-ring ring-one"/><div className="orbit-core"><svg viewBox="0 0 100 100" fill="none"><path d="M12 52h18l10-26 18 50 12-30h18" stroke="currentColor" strokeWidth="3" strokeLinejoin="round"/></svg></div><span className="orbit-label label-one">ATTENTION</span><span className="orbit-label label-two">PERSPECTIVE</span><span className="orbit-label label-three">COMMUNITY</span><i className="orbit-dot"/></div></section>
  <section className="home-snapshot" aria-label="Latest market snapshot"><div><span className="snapshot-dot"/><strong>{source==='demo'?'Sample snapshot':stale?'Collection catching up':'Latest completed snapshot'}</strong><small>{asOf?asOf.toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Awaiting data'}</small></div><div><strong>{loading?'—':number(data?.total_mentions??rows.reduce((n,r)=>n+r.mentions,0))}</strong><small>ticker mentions · 24h</small></div><div><strong>{status?.catalog?.length??'—'}</strong><small>stocks in our universe</small></div><div><strong>{watchlist.length}</strong><small>stocks on your watchlist</small></div></section>
  <div className="home-section-heading"><div><span className="eyebrow">CHOOSE YOUR NEXT MOVE</span><h2>Your market. Your way in.</h2></div><span className="muted">From the big picture to your own circle.</span></div>
  <section className="home-tiles" aria-label="Explore your workspace">{destinations.map(([key,title,headline,description,action],i)=><button key={key} className={'home-tile tile-'+key} onClick={()=>onNavigate(key)}><div className="tile-top"><span>{String(i+1).padStart(2,'0')} / {title}</span>{['community','voices'].includes(key)&&<span className="premium-badge">{key==='voices'?'Premium extras':'Premium'}</span>}<span className="tile-arrow" aria-hidden="true">↗</span></div><Illustration kind={key}/><h3>{headline}</h3><p>{description}</p><span className="tile-action">{action}<span aria-hidden="true"> →</span></span></button>)}</section>
  <section className="home-catchup"><div className="catchup-intro"><span className="eyebrow">A MOMENT TO CATCH UP</span><h2>Start with what’s<br/>getting attention.</h2><p>{data?.ranking_locked?'A few names from your free five-stock preview. Premium opens the full rankings.':'The most-mentioned names in the latest 24-hour snapshot. Attention is a starting point, not a recommendation.'}</p><button className="text-link" onClick={()=>onNavigate('market')}>See the full market pulse →</button></div><div className="catchup-stocks">{loading?<p role="status">Loading the latest snapshot…</p>:leaders.length?leaders.map((r,i)=><button key={r.ticker} onClick={()=>onTicker(r.ticker)}><span className="catchup-rank">0{i+1}</span><span><strong>${r.ticker}</strong><small>{r.name}</small></span><span className="catchup-count"><strong>{number(r.mentions)}</strong><small>mentions</small></span><span aria-hidden="true">↗</span></button>):<p>No snapshot available yet. Your workspace is ready to explore.</p>}</div></section>
  <div className="home-utilities"><span>Make this space yours.</span><button onClick={()=>onNavigate('account')}>Profile & membership ↗</button>{['owner','admin'].includes(user.role)&&<button onClick={()=>onNavigate('admin')}>Administration ↗</button>}</div>
 </div>
}
