import React,{useEffect,useRef} from 'react'
import './motion-tour.css'
function TourIcon({name}){const paths={'message-circle':'M21 11a9 9 0 0 1-9 9H3l2-5a9 9 0 1 1 16-4Z','messages-square':'M3 3h14v12H8l-5 4V3 M18 8h3v13l-5-3h-5','cpu':'M6 6h12v12H6Z M9 9h6v6H9Z M9 2v4 M15 2v4 M9 18v4 M15 18v4 M2 9h4 M2 15h4 M18 9h4 M18 15h4','memory-stick':'M3 6h18v12H3Z M7 9v6 M12 9v6 M17 9v6 M6 18v3 M10 18v3 M14 18v3 M18 18v3','network':'M9 2h6v6H9Z M2 16h6v6H2Z M16 16h6v6h-6Z M12 8v4 M5 16v-4h14v4','zap':'m13 2-9 12h7l-1 8 10-12h-7Z','snowflake':'M12 2v20 M3 7l18 10 M3 17 21 7 M9 4l3 3 3-3 M9 20l3-3 3 3','server':'M3 3h18v7H3Z M3 14h18v7H3Z M7 6v1 M7 17v1'};return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>}
export function MotionTour(){const ref=useRef(null);useEffect(()=>{
const lifecycle=new AbortController();const signal=lifecycle.signal;let frame=0,disposed=false;
const root=ref.current,scenes=[...root.querySelectorAll('.scene')],stage=root.querySelector('.stage'),motion=matchMedia('(prefers-reduced-motion: reduce)');let running=!motion.matches,elapsed=motion.matches?23000:0,last=performance.now(),active=-1,visible=false;
const clamp=v=>Math.max(0,Math.min(1,v)),ease=v=>1-Math.pow(1-clamp(v),3);
function draw(){const n=Math.min(5,Math.floor(elapsed/4000)),p=clamp((elapsed-n*4000)/4000);if(n!==active){scenes.forEach((s,i)=>{s.classList.toggle('leaving',i===active);s.classList.toggle('active',i===n);s.setAttribute('aria-hidden',String(i!==n));});active=n;}stage.style.opacity=running?Math.min(clamp(elapsed/600),clamp((24000-elapsed)/700)):1;
root.querySelector('.trace').style.strokeDasharray='100';root.querySelector('.trace').style.strokeDashoffset=String(100*(1-ease(p/.85)));if(n===0)root.querySelectorAll('[data-float]').forEach((b,i)=>{const q=ease((p-i*.15)/.55);b.style.opacity=q;b.style.transform=`translateY(${(1-q)*80-p*12}px) scale(${.85+.15*q})`;});
if(n===1)root.querySelectorAll('.block').forEach((b,i)=>{b.classList.toggle('lit',i<=Math.floor(p*7));b.style.transform=`translateY(${(1-ease((p-i*.08)/.45))*35- (i===Math.min(5,Math.floor(p*6))?5:0)}px)`;});
if(n===2){const spread=Math.min(193,root.clientWidth*.30);root.querySelectorAll('[data-research]').forEach((b,i)=>{const q=ease((p-i*.10)/.55);b.style.opacity=q;b.style.transform=`translateX(calc(-50% + ${(i-1)*spread*q}px)) translateY(${(1-q)*60+Math.abs(i-1)*10}px) rotate(${(i-1)*(1-q)*12}deg)`;});}
if(n===3)root.querySelectorAll('[data-doc]').forEach((b,i)=>{const phase=p*2.2,iShift=i-phase; b.style.zIndex=String(10+i);b.style.transform=`translateX(calc(-50% + ${iShift*65}px)) translateY(${Math.abs(iShift)*9}px) rotate(${iShift*9}deg)`;b.style.opacity=clamp(1-Math.max(0,-iShift-1)*1.8);b.querySelector('.highlight').style.transform=`scaleX(${ease((p-i*.2)/.3)})`;});
if(n===4)root.querySelectorAll('[data-voice]').forEach((b,i)=>{const q=ease(p/.7),keep=i===2||i===3;const x=[8,52,24,42,12][i],y=[30,65,125,205,230][i];b.style.left=(keep?x+(i===2?6:-7)*q:x)+'%';b.style.top=(keep?y:(y-80*q))+'px';b.style.opacity=keep?1:1-q*.92;b.style.transform=`scale(${keep?1+.06*q:1-.15*q})`;});
if(n===5){root.querySelector('.final-art').style.transform=`translateY(${(1-ease(p/.55))*25}px)`;root.querySelector('.final-art').style.opacity=ease(p/.4);}}
// Run only while visible; a soft fade bridges the end back to the first scene.
function schedule(){if(!disposed&&running&&visible&&!document.hidden&&!frame){last=performance.now();frame=requestAnimationFrame(tick);}}
function tick(now){frame=0;if(disposed||!running||!visible||document.hidden)return;const dt=Math.min(100,now-last);last=now;elapsed=(elapsed+dt)%24000;draw();frame=requestAnimationFrame(tick);}
function visibility(){if(frame){cancelAnimationFrame(frame);frame=0;}schedule();}
const observer=new IntersectionObserver(e=>{visible=e[0].isIntersecting;visibility();});observer.observe(root);
document.addEventListener('visibilitychange',visibility,{signal});
motion.addEventListener('change',()=>{running=!motion.matches;if(!running)elapsed=23000;draw();visibility();},{signal});draw();schedule();

return ()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();lifecycle.abort();};
},[]);return <section id="echo-film" ref={ref} aria-label="Explore Traders Echo in 24 seconds"><header className="mast"><span>Traders Echo</span><small>Attention becomes perspective.</small></header>
<div className="stage">
 <section className="scene active" data-n="0" aria-label="Market Pulse: conversations rising around tickers">
  <div className="art"><svg className="chart" viewBox="0 0 560 220" preserveAspectRatio="none" role="img" aria-label="Illustrative rising conversation activity, not stock prices"><path className="grid" d="M0 50H560 M0 110H560 M0 170H560"/><path className="trace" pathLength="100" d="M0 190 L45 185 L90 159 L130 172 L175 129 L215 140 L260 103 L310 116 L355 69 L400 81 L455 39 L505 46 L560 8"/></svg><div className="bubble" data-float="0" style={{"left": "8%", "top": "130px"}}><TourIcon name="message-circle"/><b>$AMD</b><span>A new conversation</span></div><div className="bubble" data-float="1" style={{"left": "30%", "top": "95px"}}><TourIcon name="messages-square"/><b>$MU</b><span>More perspectives</span></div><div className="bubble featured" data-float="2" style={{"right": "5%", "top": "40px"}}><TourIcon name="message-circle"/><b>$NVDA</b><span>Attention is building</span></div><div className="caption-tag">Conversation activity on X · Illustration</div></div>
  <div className="heading"><small>Market Pulse</small><h2>Find the names making noise.</h2><p>Follow the conversation. Find your next research starting point.</p></div>
 </section>
 <section className="scene" data-n="1" aria-hidden="true"><div className="art"><div className="network"><svg className="connections" viewBox="0 0 500 235" preserveAspectRatio="none" aria-hidden="true"><path d="M80 60H420V180H80V60 M250 60V180"/></svg><div className="block"><TourIcon name="cpu"/><b>Compute</b></div><div className="block"><TourIcon name="memory-stick"/><b>Memory</b></div><div className="block"><TourIcon name="network"/><b>Networking</b></div><div className="block"><TourIcon name="zap"/><b>Power</b></div><div className="block"><TourIcon name="snowflake"/><b>Cooling</b></div><div className="block"><TourIcon name="server"/><b>Infrastructure</b></div></div></div><div className="heading"><small>AI Supply Chain</small><h2>See how the AI economy connects.</h2><p>From the chips to the power that keeps them running.</p></div></section>
 <section className="scene" data-n="2" aria-hidden="true"><div className="art"><article className="research-card" data-research="0"><span className="number">01</span><small>Memory</small><b>MU</b><p>Broker perspectives.<br/>One concise view.</p><span className="seal">Research</span></article><article className="research-card" data-research="1"><span className="number">02</span><small>Power</small><b>AES</b><p>Company developments.<br/>Context that matters.</p><span className="seal">Research</span></article><article className="research-card" data-research="2"><span className="number">03</span><small>Equipment</small><b>ACMR</b><p>Ratings. Targets.<br/>Key takeaways.</p><span className="seal">Research</span></article></div><div className="heading"><small>Trending Research</small><h2>See what analysts are saying.</h2><p>Concise broker summaries, connected to the names you follow.</p></div></section>
 <section className="scene" data-n="3" aria-hidden="true"><div className="art"><article className="document" data-doc="0"><small>Annual report</small><h3>10-K</h3><div className="line"></div><div className="line short"></div><div className="highlight"></div><div className="line"></div><span className="seal">Original disclosure ↗</span></article><article className="document" data-doc="1"><small>Quarterly report</small><h3>10-Q</h3><div className="line"></div><div className="line short"></div><div className="highlight"></div><div className="line"></div><span className="seal">Original disclosure ↗</span></article><article className="document" data-doc="2"><small>Current report</small><h3>8-K</h3><div className="line"></div><div className="line short"></div><div className="highlight"></div><div className="line"></div><span className="seal">Original disclosure ↗</span></article></div><div className="heading"><small>SEC Filings</small><h2>Company news.<br/>Straight from the source.</h2><p>Connect the conversation with company disclosures.</p></div></section>
 <section className="scene" data-n="4" aria-hidden="true"><div className="art"><div className="focus-ring"></div><div className="voice-cloud"><div className="bubble" data-voice="0"><TourIcon name="message-circle"/><b>Another headline…</b></div><div className="bubble" data-voice="1"><TourIcon name="message-circle"/><b>Another hot take…</b></div><div className="bubble featured" data-voice="2"><TourIcon name="messages-square"/><b>$NVDA</b><span>Voices you follow</span></div><div className="bubble" data-voice="3"><TourIcon name="message-circle"/><b>$MU</b><span>A different perspective</span></div><div className="bubble" data-voice="4"><TourIcon name="message-circle"/><b>More noise…</b></div></div></div><div className="heading"><small>Tracked Voices</small><h2>Less noise. More perspective.</h2><p>Keep the voices that matter connected to the stocks you research.</p></div></section>
 <section className="scene" data-n="5" aria-hidden="true"><div className="art"><div className="final-art"><div className="mark" aria-hidden="true"><i></i><i></i><i></i></div><div className="brandname">Traders Echo</div><div className="brandstrap">Attention · Perspective · Community</div></div></div><div className="heading"><small>Your view of the AI economy</small><h2>Find the conversation.<br/>Form your own conviction.</h2><p>Explore Traders Echo.</p></div></section>
</div>
<div className="previewnote">Illustrative tour · Conversation activity, not stock-price performance</div>
</section>}
