import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import {DriveResearchAdmin} from './ResearchDrive.jsx'
function Findings({report}){return <><h3>{report.title}</h3><p className="muted">{report.firm||'Source not identified'} · Report date: {report.report_date||'Needs verification'}</p>{report.findings.map(f=><article className="panel" key={f.ticker}><strong>${f.ticker}</strong> <span className="tag">{f.stance} · author’s stance</span><p>{f.summary}</p>{f.catalysts.length>0&&<p><strong>Catalysts: </strong>{f.catalysts.join(' · ')}</p>}{f.risks.length>0&&<p><strong>Risks: </strong>{f.risks.join(' · ')}</p>}<details><summary>Source evidence · page {f.page}</summary><blockquote>{f.evidence}</blockquote></details></article>)}</>}
export function ResearchAdmin(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){try{setData(await api('/admin/research'));setError('')}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 return <section className="panel"><div className="section-head"><h2>Research inbox</h2><button className="button" onClick={load}>Refresh research</button></div><DriveResearchAdmin/><p>Email PDFs are checked every five minutes. A token-free filename and text check screens likely unrelated sector reports before AI analysis. You can override a suggested skip. Recent summaries publish automatically after source evidence, universe links and report dates pass validation. Uncertain notes stay private for review.</p><p className="muted">Analysis uses page 1 and, only if needed, its paragraph continuation on page 2. Original mailbox messages remain untouched. Report dates come from the document or a clear filename date, not the forwarding date. Analysis shares the existing $20 monthly AI ceiling, with a $15 research allowance.</p>{error&&<p className="error" role="alert">{error}</p>}{data&&<><p>Mailbox: {data.configured?'connected credential saved':'password required'} · Last worker: {data.worker?.state||'not run yet'}</p>{data.health?.issues?.length>0&&<div className="error" role="status"><strong>Import health</strong><ul>{data.health.issues.map(issue=><li key={issue}>{issue}</li>)}</ul></div>}{data.documents.length===0&&<p>No PDF attachments imported yet.</p>}{data.documents.map(d=><section className="panel" key={d.id}><div className="section-head"><h3>{d.filename}</h3><span className="tag">{d.status.replaceAll('_',' ')}</span></div><p className="muted">{d.pages} extracted pages · Research source · internal only</p>{d.error&&<p className="error">{d.error}</p>}{d.prescreen&&<p className="muted">Prescreen: {d.prescreen.reason}{d.prescreen.skip?' No AI tokens needed for the screening.':''}</p>}{['awaiting_analysis','screened_out'].includes(d.status)&&<button className="button primary" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/admin/research/'+d.id+'/analyze'+(d.prescreen?.skip?'?override=1':''),'POST');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>{d.prescreen?.skip?'Analyze anyway (uses AI credits)':'Analyze report'}</button>}{d.result&&<Findings report={d.result}/>} {d.status==='draft'&&<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await api('/admin/research/'+d.id+'/publish','POST');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>Publish reviewed summary</button>}</section>)}</>}</section>
}
export function TickerResearch({ticker}){
 const [docs,setDocs]=useState([])
 useEffect(()=>{let active=true;setDocs([]);api('/research/'+encodeURIComponent(ticker)).then(d=>{if(active)setDocs(d.documents)}).catch(()=>{});return()=>{active=false}},[ticker])
 if(!docs.length)return null
 return <details className="ticker-filings"><summary>Desk research · private admin preview ({docs.length})</summary><p className="muted">AI-generated drafts. Verify against the original report before publication. Newest report dates first.</p>{docs.map(d=><Findings key={d.id} report={d}/>)}</details>
}
