import {RadarButton} from './Engagement.jsx'
import React,{useEffect,useState,useRef} from 'react'
import {api} from './api.js'
import {dualTime} from './time.js'
import './supply-chain.css'
const fmt=n=>Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(n)
export function SupplyChain({refresh,onTicker,onPlans,renderRows}){
 const loadedWindow=useRef(null)
 const [window,setWindow]=useState(1),[data,setData]=useState(null),[error,setError]=useState(''),[sector,setSector]=useState('')
 useEffect(()=>{let active=true;if(loadedWindow.current!==window){setData(null);loadedWindow.current=window}setError('');api('/supply-chain?window='+window).then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[window,refresh])
 const selected=data?.groups.find(g=>g.sector===sector)
 const shown=selected?[selected]:(data?.groups||[])
 const stockRow=r=><div className="supply-stock-wrap" key={r.ticker}><button className="supply-stock" key={r.ticker} onClick={()=>onTicker(r.ticker,window)}><span><strong>${r.ticker}</strong><small>{r.name}</small></span><span>{fmt(r.mentions)} mentions<small>{r.change===null?'Comparison unavailable':`${r.change>0?'+':''}${r.change}% vs preceding window`}</small></span><span aria-hidden="true">↗</span></button><RadarButton ticker={r.ticker} compact/></div>
 return <div className="supply-page">
  <section className="panel supply-intro"><span className="eyebrow">FROM COMPUTE TO THE COMPANIES PUTTING IT TO WORK</span><h2>Follow attention through the AI supply chain.</h2><p>See where the conversation is concentrated, then explore the companies and collected evidence behind it.</p><div className="tabs" aria-label="Heatmap period">{[[1,'24 hours'],[7,'7 days'],[30,'30 days']].map(([n,label])=><button key={n} aria-pressed={window===n} className={window===n?'selected':''} onClick={()=>setWindow(n)}>{label}</button>)}</div><p className="muted">Colour shows share of collected ticker mentions—not price returns or bullishness. Posts mentioning several stocks count once for each ticker. Larger segments can attract more mentions.</p>{data?.as_of&&<small>Snapshot · {dualTime(data.as_of)}{data.stale?' · Collection catching up':''}</small>}</section>
  {error&&<p role="alert" className="error">{error}</p>}{!data&&!error&&<p role="status">Loading the supply chain…</p>}{data?.demo&&<p className="panel">The supply-chain map uses live collected counts. Sign in with a real account to explore it.</p>}
  <div className="supply-map">{data?.groups.map(g=><button key={g.sector} aria-pressed={!data.locked&&selected?.sector===g.sector} aria-label={data.locked?`${g.sector}, ${g.stocks} companies. Explore Premium`:undefined} className={'supply-cell '+(!data.locked&&selected?.sector===g.sector?'selected':'')} style={{'--attention':data.locked?.12:Math.min(.55,.07+g.share/100)}} onClick={()=>data.locked?onPlans():setSector(v=>v===g.sector?'':g.sector)}><span className="eyebrow">{g.stocks} covered companies</span><h3>{g.sector}</h3>{data.locked?<div className="supply-locked-metrics" aria-hidden="true"><strong>••%</strong><span>of collected ticker mentions</span><p>••• mentions · •• names measured</p><small>Premium attention insights</small></div>:<div className="supply-metrics"><strong>{g.measured?g.share+'%':'—'}</strong><span>of collected ticker mentions</span><p>{fmt(g.mentions)} mentions · {g.measured}/{g.stocks} names measured</p><small>{g.complete} names have a complete {window===1?'24-hour':window+'-day'} window</small></div>}</button>)}</div>
  {data?.locked&&!data.demo?<section className="supply-paywall"><div className="supply-fade-preview" aria-hidden="true">{[1,2,3].map(n=><div key={n}><i/><i/><i/></div>)}</div><div className="ranking-upgrade"><span className="premium-badge">Premium</span><h2>See the full AI supply chain.</h2><p>Upgrade to Premium to unlock attention shares, the top three stocks in every sector and full company rankings.</p><button className="button primary" onClick={onPlans}>Upgrade to Premium ↗</button></div></section>:data&&!data.demo?<section><div className="section-head"><div><span className="eyebrow">{selected?'SECTOR DEEP DIVE':'THE BIG PICTURE'}</span><h2>{selected?selected.sector:'Top 3 per sector'}</h2></div>{selected&&<button className="button" onClick={()=>setSector('')}>← Top 3 per sector</button>}</div><p className="muted">{selected?'Click the selected tile again to return to all sectors.':'Select a sector tile to explore its full ranking.'} Ordered by attention heat score. Missing coverage is not zero activity.</p><div className={selected?'supply-sector-detail':'supply-sector-overview'}>{shown.map(g=><section className="panel" key={g.sector}>{!selected&&<div className="section-head"><h3>{g.sector}</h3><button className="text-link" onClick={()=>setSector(g.sector)}>View all ↗</button></div>}{selected?renderRows(g.rows,window):g.rows.slice(0,3).map(stockRow)}{!g.rows.length&&<p className="muted">No saved counts in this period yet.</p>}</section>)}</div></section>:null}
 </div>
}

export function TrendingEvidence({posts=[],loading,error,windowDays=1}){
 const curated=posts.filter(p=>p.curated).slice(0,3)
 const authors=new Set(curated.map(p=>p.author.toLowerCase())).size
 return <section className="panel trending-evidence"><span className="eyebrow">WHY IT’S TRENDING · EVIDENCE CHECK</span><h3>{loading?'Finding the context…':error?'Evidence temporarily unavailable':curated.length?'What our tracked voices are discussing':'Reason not yet established'}</h3><p className="muted">{error?'Evidence could not be loaded. Try Refresh.':curated.length?`${authors} tracked ${authors===1?'voice':'voices'} in the source cards below. These views offer context, not proof of what caused attention to change.`:`No collected admin-voice post matches this stock in the last ${windowDays===1?'24 hours':windowDays+' days'}. Try a longer period. Mention activity alone does not explain a catalyst.`}</p>{curated.map(p=><article key={p.id}><a href={'https://x.com/i/web/status/'+p.id} target="_blank" rel="noreferrer">@{p.author} · {dualTime(p.ts)} ↗</a>{p.sentiment_status==='done'&&p.sentiment_reason?<><small className="block">AI interpretation of this post</small><p>{p.sentiment_reason}</p>{p.sentiment_evidence&&<blockquote>{p.sentiment_evidence}</blockquote>}</>:<p>{p.text.slice(0,240)}{p.text.length>240?'…':''}</p>}</article>)}</section>
}
