import React,{useEffect,useState} from 'react'
import {api} from './api.js'

export function Universe(){
 const [data,setData]=useState(null),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>api('/admin/stocks').then(setData)
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 const rows=data?.rows.filter(r=>(r.ticker+' '+r.name+' '+r.sector).toLowerCase().includes(q.toLowerCase()))||[]
 async function toggle(r){setBusy(true);try{await api('/admin/stocks','POST',{stocks:[{...r,active:!r.active}]});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><div className="section-head"><div><h2>AI supply-chain universe</h2><p className="muted">{data?.active||0} active · capacity 1,000 · exchange-listed symbols</p></div><input aria-label="Search stock universe" placeholder="Ticker, company or theme" value={q} onChange={e=>setQ(e.target.value)}/></div><p className="muted">A research universe, not a recommendation. Power and industrial exposure can be indirect. Every name has an inclusion reason; we do not fill the capacity with unrelated stocks. Capitalization buckets need a current market-data source.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="table-scroll"><table><thead><tr><th>Stock</th><th>Theme / reason</th><th>Status</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.ticker}><td><strong>${r.ticker}</strong><small className="block">{r.name}</small></td><td>{r.sector}<small className="block">{r.reason}</small></td><td><button className="button" disabled={busy} onClick={()=>toggle(r)}>{r.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div><p className="muted">Showing {Math.min(100,rows.length)} of {rows.length} matches. Search to narrow the list.</p><label>Import reviewed stocks (JSON)<input type="file" accept=".json,application/json" disabled={busy} onChange={async e=>{const f=e.target.files[0];if(!f)return;setBusy(true);setError('');try{const j=JSON.parse(await f.text());await api('/admin/stocks','POST',{stocks:Array.isArray(j)?j:j.stocks});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}/></label><p className="muted">Fields: ticker, name, sector, theme, reason, exchange, active. Owner access required for changes.</p></section>
}

export function Collection(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const load=()=>api('/admin/collection').then(setData)
 useEffect(()=>{let active=true;const refresh=()=>{if(document.visibilityState==='visible')api('/admin/collection').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)})};refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[])
 async function run(path){setBusy(true);setError('');try{const r=await api(path,'POST');setNotice(r.deferred?`Collection paused until ${new Date(r.retry_after*1000).toLocaleTimeString()}. It resumes on the next scheduled run after that.`:r.errors?.length?r.errors.join(' '):r.completed!=null?`${r.completed} jobs completed. Run another batch to continue.`:`${r.retried} jobs requeued.`);await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Daily collection</h2><p>{data?(data.configured?'X credential configured':'X credential not connected'):'Checking connection…'} · {data?.day}</p><p className="muted">Daily counts cover the universe. Hourly checks revisit the top ten and rotate through post samples and groups of five tracked accounts. Samples may omit posts. Refreshing this page never purchases data.</p><p role="status">Scheduler: {data?.automatic_preview?'recent heartbeat received':data?.scheduler_last_seen?'overdue — investigate scheduler':'not connected yet'}{data?.scheduler_last_seen?' · '+new Date(data.scheduler_last_seen*1000).toLocaleString():''}</p>{data?.retry_after&&<p role="status">X pacing pause until {new Date(data.retry_after*1000).toLocaleString()}. Collection resumes automatically on the next scheduled run after that.</p>}{data?.last_result&&<p>Last run: {data.last_result.completed} jobs in {data.last_result.duration_seconds}s</p>}<div className="button-row"><button className="button primary" disabled={busy||!data?.configured} onClick={()=>run('/admin/collection/tick')}>{busy?'Processing batch…':'Run next batch'}</button><button className="button" disabled={busy} onClick={()=>run('/admin/collection/retry')}>Retry failed jobs</button></div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{data?.jobs.map(j=><div className="handle" key={j.kind+j.status}><span>{j.kind} · {j.status}</span><strong>{j.n}</strong></div>)}{data?.live_jobs?.map(j=><div className="handle" key={"live"+j.kind+j.status}><span>{j.kind.replaceAll("_"," ")} · {j.status}</span><strong>{j.n}</strong></div>)}{data?.live_errors?.map((e,i)=><p className="error" key={"live-error"+i}>{e.ticker}: {e.error}</p>)}{data?.errors.map((e,i)=><p className="error" key={i}>{e.ticker}: {e.error}</p>)}</section>
}
