import React,{useEffect,useState} from 'react'
import {api} from './api.js'

export function ApiAddon({user}){
 const [data,setData]=useState(null),[key,setKey]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setData(await api('/customer-api/status'))}
 useEffect(()=>{let active=true;setData(null);setKey('');if(user&&!user.demo)api('/customer-api/status').then(d=>{if(active)setData(d)}).catch(()=>{});return()=>{active=false}},[user?.id])
 async function run(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel api-addon" style={{marginTop:24,padding:24}} aria-label="Optional API add-on"><div className="section-head"><div><span className="eyebrow">OPTIONAL ADD-ON</span><h3>Tradersecho API</h3><p className="muted">Bring Tradersecho stock sentiment scores into your own tools.</p></div><div className="pricing-amount">+$5<small>/ month</small></div></div><p>10,000 requests/month · Up to 10 requests/minute · Read-only access</p><p className="muted">Available with paid Premium, Pro or Founder. Billed separately each month. Aggregated sentiment only: no X posts, authors, links or research text. Uses existing AI analysis; no extra X or AI requests. Personal or internal use only.</p><div className="button-row"><button className="button primary" disabled={busy||!data?.enabled||!data?.eligible||data?.subscribed} onClick={()=>run(async()=>{const result=await api('/customer-api/checkout','POST',{});location.assign(result.url)})}>{data?.subscribed?'API subscription active':data?.enabled?data?.eligible?'Add API access':'Paid membership required':'API access coming soon'}</button><a className="button" href="/api-docs.html" target="_blank" rel="noopener noreferrer">Read API documentation ↗</a>{data?.subscribed&&<button className="button" disabled={busy} onClick={()=>run(async()=>{const result=await api('/billing/portal','POST',{});location.assign(result.url)})}>Manage API billing</button>}</div>{!data?.enabled&&<p className="muted">Not available for purchase yet. No API charge is added to your membership.</p>}{data?.subscribed&&<><p>{data.used.toLocaleString()} / {data.limit.toLocaleString()} requests used · {data.month} UTC</p><div className="button-row"><button className="button" disabled={busy||!data.enabled||!data.eligible} onClick={()=>run(async()=>{if(data.has_key&&!window.confirm('Replace your API key? The previous key will stop working immediately.'))return;const result=await api('/customer-api/key','POST',{});setKey(result.key);await load()})}>{data.has_key?'Replace API key':'Create API key'}</button>{data.has_key&&<button className="button" disabled={busy} onClick={()=>run(async()=>{await api('/customer-api/key','DELETE');setKey('');await load()})}>Revoke API key</button>}</div></>}{key&&<label>Copy your key now. It is shown only once.<input aria-label="New API key" readOnly value={key} style={{width:'100%'}}/></label>}{error&&<p className="error" role="alert">{error}</p>}</section>
}
