import {useEffect,useState} from 'react'
import {api} from './api.js'
import {CompanyLogo} from './CompanyLogo.jsx'
import './industry-radar.css'
const clock=t=>t?new Date(t*1000).toLocaleString():'Not checked yet'
export function IndustryRadar(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all')
 const load=()=>api('/admin/industry-radar').then(setData)
 useEffect(()=>{let active=true;const refresh=()=>api('/admin/industry-radar').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')refresh()},60000);return()=>{active=false;clearInterval(t)}},[])
 const rows=(data?.items||[]).filter(x=>x.status==='complete'&&(filter==='all'||x.result?.topic===filter))
 return <div className="radar"><header className="radar-hero"><div><span className="eyebrow">PRIVATE PILOT · ADMIN ONLY</span><h2>AI Industry Radar</h2><p>What changed. Who could be affected. What still needs confirmation.</p><small>Memory · Optical networking · Advanced packaging</small></div><div className="radar-scope" aria-hidden="true"><i/><i/><b>◎</b></div></header>
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="radar-stats"><section><small>Separate monthly allowance</small><strong>${data?.budget?.accounted?.toFixed(2)||'0.00'} / $20</strong><small>Provider-reported: ${data?.budget?.actual?.toFixed(2)||'0.00'} · {data?.budget?.estimated_attempts||0} estimated attempts</small></section><section><small>Source checks</small><strong>{data?.sources?.filter(s=>s.state==='ok').length||0} / {data?.sources?.length||8} responding</strong><small>Coverage is partial; source status below</small></section><section><small>Last worker run</small><strong>{data?.stalled?'Needs attention':'Running'}</strong><small>{clock(data?.last_run?.at)}</small></section></div>
 <div className="radar-controls"><label>Topic <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All pilot themes</option><option value="hbm">Memory / HBM</option><option value="optical-networking">Optical networking</option><option value="advanced-packaging">Advanced packaging</option></select></label><button className="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api('/admin/industry-radar/run','POST');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'Checking sources…':'Run bounded check'}</button></div>
 {data?.last_run?.analysis?.state==='budget_paused'&&<p className="error">The private radar has reached its allowance. Brokerage imports have their own budget and continue independently.</p>}
 {!rows.length&&<section className="panel"><h3>No validated developments in this view yet.</h3><p>The scanner will fill this with evidence-checked analyses. Unreadable sources and unsupported claims are skipped, not published as speculation.</p></section>}
 <div className="radar-feed">{rows.map(item=>{const r=item.result;return <article className="radar-card" key={item.id}><div className="radar-labels"><span>{r.topic.replaceAll('-',' ')}</span><span className={r.kind==='rumour'?'radar-rumour':''}>{r.kind==='rumour'?'UNCONFIRMED RUMOUR':r.kind.toUpperCase()}</span><span>{r.novelty.replaceAll('_',' ')}</span></div><h3>{r.headline}</h3><small>{item.source} · {item.day||'Publication date unknown'} · Found {clock(item.created)}</small><p className="radar-summary">{r.summary}</p><div className="radar-change"><b>What changed</b><p>{r.what_changed}</p><small>Compared only with available saved context, not all market information.</small></div><div className="radar-links">{r.readthroughs.map((l,i)=><div key={l.ticker+i} className={'radar-link '+l.direction}><div><CompanyLogo ticker={l.ticker}/><a href={'/stocks/'+l.ticker}>${l.ticker}</a><span>{l.direction} · {l.relationship==='inferred'?'TradersEcho inference':'Directly mentioned'}</span></div><p>{l.reason}</p><small>{l.caveat}</small></div>)}</div>{!r.readthroughs.length&&<p className="muted">No company relationship met the evidence threshold.</p>}<footer><div><b>Expected timing</b><p>{r.timing}</p></div><div><b>Watch next</b><p>{r.next_check}</p></div></footer><p className="muted">{r.uncertainty}</p><details><summary>Source support & comparison</summary><blockquote>{r.evidence}</blockquote>{item.url&&<a href={item.url} target="_blank" rel="noreferrer">Read original source ↗</a>}{!item.url&&<p>Private imported research. Original document stays private.</p>}<p>Compared with {r.compared_to.length} saved evidence records.</p>{r.readthroughs.map((l,i)=><p key={i}><b>{l.ticker} relationship evidence:</b> {l.basis_quote}</p>)}</details></article>})}</div>
 <details className="panel" open><summary>Collection health & budget rules</summary><p>{data?.cadence}</p><p>Page visits do not spend AI credits. This $20 pilot is separate from the existing AI allowance. Provider costs are settled after each attempt; unknown costs are shown as conservative estimates. Failed items are skipped without automatic paid retries. Public pages and Catalyst scores are unchanged.</p><div className="radar-source-grid">{data?.sources?.map(s=><div key={s.source}><b>{s.source}</b><span>{s.state.replaceAll('_',' ')}</span><small>{s.error||s.article_error||`${s.added||0} relevant items added on last check`}</small><small>{clock(s.at)}</small></div>)}</div><p>{data?.counts?.map(c=>`${c.status}: ${c.count}`).join(' · ')}</p>{data?.last_run?.error&&<p className="error">Worker: {data.last_run.error}</p>}<details><summary>Skipped analyses</summary>{data?.items?.filter(x=>x.status==='skipped').map(x=><p key={x.id}>{x.source} · {x.title} · {x.error}</p>)}</details></details></div>
}
