import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import './insights-admin.css'
import {InsightGallery} from './InsightGallery.jsx'
const date=value=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z')):'Undated source'
function Timeline({items,sources}){
 return <ol className="insight-timeline">{items.map((item,i)=><li key={(item.source||'')+item.title+i}><div className="insight-date"><span>{item.when}</span><small>{item.status||item.scope}</small></div><div className="insight-event"><h3>{item.title}</h3><p>{item.expectation}</p><div className="insight-source">{[item.source,item.also_source].filter(id=>sources[id]).map(id=><span key={id}>{sources[id].url?<a href={sources[id].url} target="_blank" rel="noreferrer">{sources[id].name} ↗</a>:sources[id].name} · {date(sources[id].date)}<small>{sources[id].kind}</small></span>)}</div>{item.watch&&<p className="muted"><strong>Next confirmation: </strong>{item.watch}</p>}</div></li>)}</ol>
}
export function InsightsAdmin({member=false}){
 const [running,setRunning]=useState(false),[runStatus,setRunStatus]=useState('')
 async function checkUpdates(){setRunning(true);setRunStatus('Checking sources and up to three notes…');try{const r=await api('/admin/insights-run','POST');setRunStatus(r.state==='cooldown'?'A check recently ran. The hourly schedule will continue automatically.':`Check finished: ${(r.analysis||[]).map(x=>x.state.replaceAll('_',' ')).join(', ')}. The hourly schedule continues automatically.`)}catch(e){setRunStatus(e.message)}finally{setRunning(false)}}
 const [article,setArticle]=useState(null),[error,setError]=useState(''),[topics,setTopics]=useState([]),[slug,setSlug]=useState(null)
 useEffect(()=>{let active=true;api(member?'/insights':'/admin/insights').then(d=>{if(active)setTopics(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[member])
 useEffect(()=>{let active=true;setArticle(null);setError('');if(!slug)return()=>{active=false};api((member?'/insights/':'/admin/insights/')+slug).then(d=>{if(active)setArticle(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[slug,member])
 if(error)return <p className="error" role="alert">{error}</p>
 if(!slug)return topics.length?<>{!member&&<div className="insight-worker-controls"><button type="button" disabled={running} onClick={checkUpdates}>{running?'Checking…':'Check for developments'}</button><span role="status">{runStatus||'Automatic checks run hourly within the research budget.'}</span></div>}<InsightGallery topics={topics} onSelect={setSlug}/></>:<p role="status">Loading topics…</p>
 if(!article)return <p role="status">Loading topic research…</p>
 const sources=Object.fromEntries(article.sources.map(s=>[s.id,s]))
 return <article className="insights-admin"><button type="button" className="insight-back" onClick={()=>setSlug(null)}>← All AI Insights</button><div key={slug}><div className="insight-opening-grid"><div className="insight-topic-column"><div className="insight-beneficiary-heading"><span className="eyebrow">UNDERSTAND THE THEME</span><h2>What are we talking about?</h2></div><section className="panel insight-intro"><span className="eyebrow">{member?'AI INSIGHTS':'AI INSIGHTS · ADMIN PREVIEW'}</span><h2>{article.title}</h2><div className="insight-meta"><span className="tag">{member?'Pro':'Admin only'}</span><span>Evidence through {date(article.evidence_through)}</span><span>Reviewed {date(article.reviewed)}</span></div><p className="insight-lead">{article.intro}</p><div className="insight-distinction"><h3>One theme. Different stages.</h3><p>{article.distinction}</p></div><p>{article.summary}</p></section></div><aside className="insight-beneficiaries" aria-label="Potential beneficiaries"><div className="insight-beneficiary-heading"><span className="eyebrow">FOLLOW THE OPPORTUNITY</span><h2>Potential beneficiaries</h2></div>{article.beneficiaries.map(b=><article className="insight-beneficiary-card" key={b.ticker}><div className="insight-beneficiary-title"><a className="insight-ticker" href={'/stocks/'+b.ticker}>${b.ticker} ↗</a><h3>{b.name}</h3></div><p>{b.short_reason||b.why}</p><details><summary>More</summary><div className="insight-beneficiary-expanded"><span className="tag">{b.stage}</span><div className="insight-beneficiary-timing"><small>EXPECTED TIMING</small><p>{b.timing}</p></div><p><strong>Why it matters: </strong>{b.why}</p><p><strong>What needs to happen: </strong>{b.watch}</p><div className="insight-source">{[b.source,b.also_source].filter(Boolean).map(id=><span key={id}>{sources[id].name} · {date(sources[id].date)}</span>)}</div></div></details></article>)}<details className="insight-beneficiary-context"><summary>Wider industry context</summary><p>{article.beneficiary_context}</p></details></aside></div>
 {article.guide&&<section className="panel insight-research-guide"><span className="eyebrow">THE INVESTMENT CONNECTION</span><h2>What would make this theme matter?</h2><p className="insight-lead">{article.guide.thesis}</p><div className="insight-guide-grid"><div><h3>Follow these signals</h3><ul>{article.guide.watch_metrics.map(x=><li key={x}>{x}</li>)}</ul></div><div><h3>What could weaken the thesis?</h3><ul>{article.guide.invalidation.map(x=><li key={x}>{x}</li>)}</ul></div></div><details><summary>Explain the terminology</summary><dl className="insight-glossary">{Object.entries(article.guide.glossary).map(([term,meaning])=><React.Fragment key={term}><dt>{term}</dt><dd>{meaning}</dd></React.Fragment>)}</dl></details></section>}
 <section className="panel"><span className="eyebrow">WHAT COMES NEXT</span><h2>Upcoming expectations</h2><p className="muted">Dates below are the expected milestone windows; each entry shows when its source published that view.</p>{article.outlook?.length?<Timeline items={article.outlook} sources={sources}/>:<p>No dated forward milestone is supported by the sources currently collected. Follow the open questions below.</p>}
 {!!article.watchlist?.length&&<details open><summary>Developments without a firm date ({article.watchlist.length})</summary><Timeline items={article.watchlist} sources={sources}/></details>}
 {!!article.unconfirmed?.length&&<details><summary>Past targets awaiting confirmation ({article.unconfirmed.length})</summary><p className="muted">The target window has passed. That alone does not mean the milestone happened.</p><Timeline items={article.unconfirmed} sources={sources}/></details>}
 {!!article.history?.length&&<details><summary>What was already known ({article.history.length})</summary><Timeline items={article.history} sources={sources}/></details>}</section>
 {article.guide&&<section className="panel"><h2>Where the debate remains open</h2><ul>{article.guide.debates.map(x=><li key={x}>{x}</li>)}</ul><p className="muted">These are questions to test against new evidence, not claims that a particular outcome will occur.</p></section>}
 <div className="insight-bottom"><section className="panel"><h2>Questions to follow</h2><ul>{article.questions.map(q=><li key={q}>{q}</li>)}</ul></section><section className="panel"><h2>Source notes</h2>{article.sources.map(s=><div className="insight-note" key={s.id}><strong>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>:s.name} · {date(s.date)}</strong><p>{s.label}</p><small className="muted">{s.kind}</small></div>)}</section></div><p className="muted">{article.editorial}</p></div></article>
}
