import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import './insights-admin.css'
import {InsightGallery} from './InsightGallery.jsx'
const date=value=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T12:00:00Z')):'Undated source'
export function InsightsAdmin({member=false}){
 const [article,setArticle]=useState(null),[error,setError]=useState(''),[topics,setTopics]=useState([]),[slug,setSlug]=useState(null)
 useEffect(()=>{let active=true;api(member?'/insights':'/admin/insights').then(d=>{if(active)setTopics(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[member])
 useEffect(()=>{let active=true;setArticle(null);setError('');if(!slug)return()=>{active=false};api((member?'/insights/':'/admin/insights/')+slug).then(d=>{if(active)setArticle(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[slug,member])
 if(error)return <p className="error" role="alert">{error}</p>
 if(!slug)return topics.length?<InsightGallery topics={topics} onSelect={setSlug}/>:<p role="status">Loading topics…</p>
 if(!article)return <p role="status">Loading private topic starter…</p>
 const sources=Object.fromEntries(article.sources.map(s=>[s.id,s]))
 return <article className="insights-admin"><button type="button" className="insight-back" onClick={()=>setSlug(null)}>← All AI Insights</button><div key={slug}><div className="insight-opening-grid"><div className="insight-topic-column"><div className="insight-beneficiary-heading"><span className="eyebrow">UNDERSTAND THE THEME</span><h2>What are we talking about?</h2></div><section className="panel insight-intro"><span className="eyebrow">{member?'AI INSIGHTS':'AI INSIGHTS · PRIVATE STARTER'}</span><h2>{article.title}</h2><div className="insight-meta"><span className="tag">{member?'Pro':'Admin only'}</span><span>Evidence through {date(article.evidence_through)}</span><span>Reviewed {date(article.reviewed)}</span></div><p className="insight-lead">{article.intro}</p><div className="insight-distinction"><h3>One theme. Different stages.</h3><p>{article.distinction}</p></div><p>{article.summary}</p></section></div><aside className="insight-beneficiaries" aria-label="Potential beneficiaries"><div className="insight-beneficiary-heading"><span className="eyebrow">FOLLOW THE OPPORTUNITY</span><h2>Potential beneficiaries</h2></div>{article.beneficiaries.map(b=><article className="insight-beneficiary-card" key={b.ticker}><div className="insight-beneficiary-title"><a className="insight-ticker" href={'/stocks/'+b.ticker}>${b.ticker} ↗</a><h3>{b.name}</h3></div><p>{b.short_reason||b.why}</p><details><summary>More</summary><div className="insight-beneficiary-expanded"><span className="tag">{b.stage}</span><div className="insight-beneficiary-timing"><small>EXPECTED TIMING</small><p>{b.timing}</p></div><p><strong>Why it matters: </strong>{b.why}</p><p><strong>What needs to happen: </strong>{b.watch}</p><div className="insight-source">{[b.source,b.also_source].filter(Boolean).map(id=><span key={id}>{sources[id].name} · {date(sources[id].date)}</span>)}</div></div></details></article>)}<details className="insight-beneficiary-context"><summary>Wider industry context</summary><p>{article.beneficiary_context}</p></details></aside></div>
 <section className="panel"><span className="eyebrow">WHAT IS EXPECTED, AND WHEN</span><h2>The development timeline</h2><p className="muted">{article.automatic_updates||0} automatic research updates · Source-dated expectations. Future milestones are forecasts, not completed events.</p><ol className="insight-timeline">{article.timeline.map((item,i)=><li key={item.title}><div className="insight-date"><span>{item.when}</span><small>{item.scope}</small></div><div className="insight-event"><h3>{item.title}</h3><p>{item.expectation}</p><div className="insight-source">{[item.source,item.also_source].filter(Boolean).map(id=><span key={id}>{sources[id].name} · {date(sources[id].date)}<small>{sources[id].kind}</small></span>)}</div>{item.watch&&<p className="muted"><strong>What to watch: </strong>{item.watch}</p>}</div></li>)}</ol></section>
 <div className="insight-bottom"><section className="panel"><h2>Questions to follow</h2><ul>{article.questions.map(q=><li key={q}>{q}</li>)}</ul></section><section className="panel"><h2>Source notes</h2>{article.sources.map(s=><div className="insight-note" key={s.id}><strong>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a>:s.name} · {date(s.date)}</strong><p>{s.label}</p><small className="muted">{s.kind}</small></div>)}</section></div><p className="muted">{article.editorial}</p></div></article>
}
