import {RadarButton} from './Engagement.jsx'
import {dualTime} from './time.js'
import React,{useEffect,useState} from 'react'
import {api} from './api.js'
function ActivityEvidence({row:r,rank}){
 const measured=r.state==='measured',values=r.spark||[],max=Math.max(1,...values)
 const delta=measured?r.mentions-r.previous:0
 return <div className="intraday-evidence">
  <span className="eyebrow">WHY #{rank} · ATTENTION EVIDENCE</span>
  {measured?<><p className="activity-explanation"><strong>{r.previous.toLocaleString()} → {r.mentions.toLocaleString()} mentions</strong><span>{delta>0?`${delta.toLocaleString()} more mentions`:delta<0?`${Math.abs(delta).toLocaleString()} fewer mentions`:'The same mention volume'} in the latest three completed hours versus the preceding three.</span></p>
  {values.length===6&&<div className="activity-plot" role="img" aria-label={`Hourly X mentions, oldest to newest: ${values.join(', ')}. First three bars are the previous period; last three are the latest period.`}>{values.map((n,i)=><div className={'activity-column '+(i>=3?'recent':'prior')} key={i}><span>{n.toLocaleString()}</span><div className="activity-track"><i style={{height:n===0?'0':`${Math.max(2,n/max*100)}%`}}/></div></div>)}</div>}
  <div className="activity-periods"><span>Previous 3 hours</span><span>Latest 3 hours</span></div>
  <p className="activity-caption">Heat score <strong>{r.heat}</strong> combines mention volume and acceleration to place this stock #{rank} among the monitored intraday names.{r.previous===0?' No mentions in the previous period; percentage growth is not defined.':r.previous<10?' The previous period had fewer than 10 mentions, so percentage changes can look unusually large.':''}</p>
  <small>Measured X activity · not a verified news catalyst or price move</small></>:<><p>A tracked voice mentioned this stock recently.</p><small>A complete six-hour count comparison is not available yet; no measured heat score is assigned.</small></>}
 </div>
}
export function Intraday({refresh,onTicker,onPlans,renderRows,onData}){
 const [data,setData]=useState(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;api('/intraday').then(d=>{if(active){setData(d);onData?.(d);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[refresh,onData])
 return <section className="panel"><span className="eyebrow">THE CONVERSATION AS IT DEVELOPS</span><h2>Intraday leaders & fresh takes</h2><p className="muted">Hourly checks of selected leaders and stocks mentioned by admin voices. Compare the latest three completed hours with the preceding three. Collection budgets can delay updates.</p>{error&&<p role="alert" className="error">{error}</p>}{!data&&!error&&<p role="status">Loading intraday activity…</p>}{data&&!data.rows.length&&<p>No fresh hourly counts or admin posts yet. The 24-hour rankings remain available above.</p>}<div className="intraday-grid">{data?.rows.slice(0,2).map((r,i)=><article className="panel intraday-leader" key={r.ticker} onClick={e=>{if(!e.target.closest('a,button'))onTicker(r.ticker)}}><div className="tile-heading"><button className="text-link" onClick={()=>onTicker(r.ticker)}><h3>${r.ticker} ↗</h3></button><div className="tile-heading-actions"><RadarButton ticker={r.ticker} tile/><span className="intraday-rank" aria-label={`Rank ${i+1}`}>{String(i+1).padStart(2,'0')}</span></div></div><p>{r.name}</p>{r.state==='measured'?<><strong>{r.mentions.toLocaleString()} mentions · last 3 hours</strong><p className="positive">{r.change!==null?`${r.change>0?'+':''}${r.change}% vs previous 3 hours`:r.previous===0&&r.mentions>0?'New attention · no prior mentions':'No previous activity'}</p><small className="muted">Through {dualTime(r.as_of)} · Heat {r.heat}</small></>:<p className="muted">Fresh voice mention · awaiting a budgeted count check</p>}<ActivityEvidence row={r} rank={i+1}/>{r.posts.length?r.posts.slice(0,1).map(p=><div className="post" key={p.id}><small className="muted block">Latest collected admin take</small><strong>@{p.author}</strong><small className="block">{dualTime(p.ts)}</small><p>{p.text.slice(0,320)}{p.text.length>320?'…':''}</p><a href={'https://x.com/i/web/status/'+p.id} target="_blank" rel="noreferrer">Read original on X ↗</a></div>):null}</article>)}</div>{data?.rows.length>2&&renderRows(data.rows.slice(2,20))}{data?.locked&&data.total>data.rows.length&&<div className="ranking-upgrade intraday-upgrade"><h3>Explore every intraday candidate</h3><p>Your preview includes {data.rows.length} of {data.total} candidates.</p><button className="button primary" onClick={onPlans}>Explore Premium</button></div>}<p className="muted">Posts offer research context; they do not establish why a stock’s attention changed. Rankings cover monitored candidates only. Opening this view reads saved data.</p></section>
}
