import {useEffect,useState} from 'react'
import {api} from './api.js'
import './options-activity.css'
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n)
const clock=t=>t?new Date(t*1000).toLocaleString(): 'Awaiting first scan'
const sideName={ask:'Ask-side dominant',bid:'Bid-side dominant',mixed:'Mixed execution',complex:'Multi-leg / complex'}
export function OptionsActivity(){
 const [sampling,setSampling]=useState(false),[sampleNote,setSampleNote]=useState('')
 const [data,setData]=useState(null),[error,setError]=useState(''),[filter,setFilter]=useState(''),[side,setSide]=useState('all')
 useEffect(()=>{let active=true;const load=()=>api('/admin/options-activity').then(d=>{if(active){setData(d);setError('')}}).catch(e=>{if(active)setError(e.message)});load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},60000);return()=>{active=false;clearInterval(timer)}},[])
 const rows=(data?.events||[]).filter(e=>e.ticker.includes(filter.toUpperCase())&&(side==='all'||side===e.side)),leaders=[...rows].sort((a,b)=>b.premium-a.premium).slice(0,3)
 return <div className="oa"><header className="oa-hero"><div><span className="eyebrow">PRIVATE EXPERIMENT · ADMIN ONLY</span><h2>Follow the premium.</h2><p>Large options activity across our universe. See the contract, the size and where it traded.</p></div><div className="oa-orbit" aria-hidden="true"><span>$</span></div></header>
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="oa-metrics"><div><small>Universe</small><strong>{data?.universe??'—'} names</strong></div><div><small>Scan cadence</small><strong>10 minutes</strong></div><div><small>Session</small><strong>{data?(data.session_open?'US market hours':'Outside session'):'Loading…'}</strong></div><div><small>Requests this quota day</small><strong>{data?.requests_today??0} / 500</strong></div></div>
 <div className="oa-health"><b>{data?.worker?.state?.replaceAll('_',' ')||'Waiting for first hosted scan'}</b><span>Last attempt: {clock(data?.worker?.at)}</span><span>Scanned through: {clock(data?.through)}</span>{data?.pending&&<strong>Incomplete window — continuation queued</strong>}{data?.worker?.http_status&&<strong>Provider response: {data.worker.http_status}</strong>}</div>
 <div className="oa-controls"><button className="button" disabled={sampling} onClick={async()=>{setSampling(true);try{const r=await api('/admin/options-activity/sample',{method:'POST'});setSampleNote('Saved '+r.matched+' universe events from the latest provider sample. Event times show their actual age.');setData(await api('/admin/options-activity'))}catch(e){setSampleNote(e.message)}finally{setSampling(false)}}}>{sampling?'Checking…':'Load latest sample'}</button>{sampleNote&&<p role="status">{sampleNote}</p>}<label>Find a ticker <input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="NVDA, MU… (one at a time)"/></label><label>Execution <select value={side} onChange={e=>setSide(e.target.value)}><option value="all">All activity</option>{Object.entries(sideName).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label></div>
 <div className="oa-leaders">{leaders.map(e=><article className={'oa-card '+e.side} key={e.id}><div className="oa-card-top"><b>${e.ticker}</b><span>{e.premium>=1000000?'$1M+ PREMIUM':'LARGE PREMIUM'}</span></div><strong className="oa-amount">{money(e.premium)}</strong><p>{e.type.toUpperCase()} · ${e.strike} · {e.expiry}</p><div className="oa-bar" aria-label={`${e.ask_pct}% ask side, ${e.bid_pct}% bid side`}><i style={{width:e.ask_pct+'%'}}/><em style={{width:e.bid_pct+'%'}}/></div><small>{sideName[e.side]} · {e.ask_pct}% ask / {e.bid_pct}% bid</small><footer>{clock(e.at)} {e.sweep?'· Sweep':''}</footer></article>)}</div>
 {data&&!rows.length&&<div className="oa-empty"><strong>No matching large-premium events collected yet.</strong><p>The scanner runs during US regular hours. This preview will fill with saved observations; refreshing this page makes no UW requests.</p></div>}
 <section className="panel"><div className="section-head"><h3>Activity tape</h3><small>Latest 200 events · past 7 days</small></div><div className="oa-table"><table><thead><tr>{['Time','Ticker','Premium','Contract','Execution','Context'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{clock(e.at)}</td><td><b>${e.ticker}</b></td><td className="oa-cash">{money(e.premium)}</td><td>{e.type.toUpperCase()} ${e.strike}<small>{e.expiry}</small></td><td><span className={'oa-pill '+e.side}>{sideName[e.side]}</span></td><td>{e.sweep?'Sweep · ':''}{e.rule}<small>Size {e.size||'—'} · OI {e.open_interest||'—'}</small></td></tr>)}</tbody></table></div></section>
 <details className="panel oa-method"><summary>Collection rules & how to read this preview</summary><p>Every 10 minutes during 09:30–16:00 New York time, one shared UW flow-alert scan checks the market and retains only our universe. Minimum event premium: $100,000. Up to five pages per run; unfinished windows continue on the next run. Maximum 500 requests per quota day, within the shared 32,000 cap. Weekday holidays follow the clock gate; no fresh market data is expected then.</p><p>Green means at least 70% ask-side premium, amber at least 70% bid-side; complex and mixed executions stay separate. These describe execution, not a confirmed opening trade or investment direction. Large premium is an absolute threshold, not yet a historical unusualness score. Alerts may overlap; their premiums are not added into a market total.</p><p>Events are deduplicated and kept for 30 days. This screen reads saved data every minute. No AI calls, no customer access and no changes to Signal Lab scores.</p></details></div>
}
