import './referrals.css'
import React,{useEffect,useState} from 'react'
import {api} from './api.js'
const labels={joined:'Joined',waiting:'Waiting for qualification',applying:'Preparing reward',rewarded:'Reward earned',waiting_reward:'Earned · waiting for existing discount to finish',annual_limit:'Annual reward limit reached',ineligible:'Not eligible',reversed:'Reward cancelled',review:'Payment check pending',already_premium:'Already has permanent Premium access'}
export function Referrals({user}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[copied,setCopied]=useState(false)
 useEffect(()=>{let active=true;if(!user.demo)api('/referrals').then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[user.id,user.demo,user.email_verified])
 if(user.demo)return null
 return <section className="panel universe" aria-label="Invite friends"><span className="eyebrow">BETTER TOGETHER</span><h2>Invite friends. Earn Premium.</h2><p>Earn one month of Premium when a new friend joins through your link and qualifies with a paid monthly or annual plan.</p>{user.referral_active&&<p className="positive">Your referral Premium access lasts until {new Date(user.referral_ends_at*1000).toLocaleDateString()}.</p>}{data?<><div className="referral-link-row"><label>Your personal invitation link<input readOnly value={data.url} onFocus={e=>e.target.select()}/></label><button className="button primary" onClick={async()=>{try{await navigator.clipboard.writeText(data.url);setCopied(true)}catch{setError('Select and copy the invitation link above.')}}}>{copied?'Copied':'Copy invitation link'}</button></div>{!data.verified&&<p className="muted">Verify your email before sharing your link to qualify for rewards.</p>}<div className="divider"/><h3>Your referrals</h3>{data.items.length?<div className="table-scroll"><table><thead><tr><th>Invitation</th><th>Progress</th><th>Earliest qualification</th></tr></thead><tbody>{data.items.map((r,i)=><tr key={i}><td>Friend {data.items.length-i}</td><td>{labels[r.state]||'Checking eligibility'}</td><td>{r.eligible_after?new Date(r.eligible_after*1000).toLocaleDateString():'After their first payment'}</td></tr>)}</tbody></table></div>:<p className="muted">Your friends’ progress will appear here after they create an account through your link.</p>}</>:<p role="status">{error||'Loading your invitation link…'}</p>}<details><summary>How rewards work</summary><p>Rewards qualify 45 days after the first successful payment, excluding any trial. The friend must remain subscribed with no refunds or disputes; monthly plans require two paid billing periods. One reward per new customer, up to six per calendar year (UTC). Self-referrals and shared payment cards are excluded.</p><p>Free members receive 30 days of Premium, added after any active trial or referral access. Monthly members receive one future monthly payment covered. Annual members receive $9 off a future renewal. No cash payout. Founder memberships and API add-ons do not qualify; members with permanent complimentary or Founder access cannot earn additional access.</p><p>Rewards wait while an event promotion is active. Refunded or disputed purchases cancel pending rewards and may remove unused rewards. Referral links are remembered for 30 days in this browser; the last invitation used before registration applies.</p></details>{error&&data&&<p className="error" role="alert">{error}</p>}</section>
}
