import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import {SignalRadar} from './SignalLab.jsx'
import {rankSignals} from './signalRanking.mjs'
import './signal-overview.css'
const number=v=>v==null?'—':Number(v.toFixed(1))
function Total({stock}){return <><strong>{number(stock.total)}</strong><small>{stock.available===5?' / 500':` points · ${stock.available}/5 available`}</small></>}
function Leaders({title,caption,rows,activity=false}){return <section className="lab-leaders"><div className="section-head"><div><h2>{title}</h2><p className="muted">{caption}</p></div></div><div className="lab-leader-grid">{rows.slice(0,3).map((s,i)=><article className="panel lab-leader" key={s.ticker}><div className="section-head"><div><strong>${s.ticker}</strong><small className="block muted">{s.name}</small></div><span className="signal-rank">0{i+1}</span></div><SignalRadar axes={s.axes}/><div className="lab-card-score">{activity?<><strong>{number(s.activity)}</strong><small> / 100 X activity</small></>:<Total stock={s}/>}</div><small className="muted">{s.available<5?'Partial coverage · ':''}{s.stale?'Last saved view':'Latest saved view'}</small></article>)}</div>{!rows.length&&<p className="muted">Waiting for saved scores.</p>}</section>}
export function SignalOverview(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('total')
 useEffect(()=>{let active=true;const load=()=>api('/admin/signal-lab-overview').then(d=>{if(active){setData(d);setError('')}}).catch(e=>{if(active)setError(e.message)});load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},120000);return()=>{active=false;clearInterval(timer)}},[])
 const ranked=rankSignals(data?.stocks),rows=(sort==='activity'?ranked.byActivity:ranked.rows).filter(s=>(s.ticker+' '+s.name).toLowerCase().includes(query.toLowerCase()))
 return <section className="lab-overview"><span className="eyebrow">ADMIN PREVIEW · SIGNAL LAB</span><h1>Find the names worth a closer look.</h1><p className="muted">Two ways to explore: the strongest X activity and the highest combined indicator scores.</p>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Loading saved scores…</p>}{data&&<><Leaders title="Leading the conversation" caption="Top 3 by X activity" rows={ranked.byActivity} activity/><Leaders title="Highest overall points" caption="Five indicators · up to 500 points" rows={ranked.byTotal}/><p className="lab-coverage-note">Complete scores rank first. While history builds, partial scores are ordered by coverage, then available points. Missing indicators stay unavailable. The total combines the displayed scores; it is not a probability or a bullish/bearish direction.</p><section className="panel"><div className="section-head"><div><h2>Signal overview</h2><p className="muted">{ranked.rows.length} names with saved observations</p></div><div className="lab-filters"><input aria-label="Search Signal Lab stocks" placeholder="Ticker or company" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort Signal Lab" value={sort} onChange={e=>setSort(e.target.value)}><option value="total">Overall points</option><option value="activity">X activity</option></select></div></div><div className="table-scroll"><table className="lab-comparison"><colgroup><col className="lab-rank-col"/><col className="lab-stock-col"/><col className="lab-shape-col"/>{Array.from({length:5},(_,i)=><col key={i}/>)}<col className="lab-total-col"/></colgroup><thead><tr><th>#</th><th>Stock</th><th className="lab-shape-heading">Signal shape</th><th>Price</th><th>Volume</th><th>Options</th><th>X activity</th><th>Catalyst</th><th>Total</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.ticker}><td>{i+1}</td><td className="lab-stock-cell"><strong>${s.ticker}</strong><small className="lab-company-name muted" title={s.name}>{s.name}</small></td><td className="lab-table-radar"><SignalRadar axes={s.axes} compact/></td>{s.axes.map(a=><td key={a.name} title={a.reason}><b>{number(a.score)}</b>{a.score==null&&<small className="block muted">Building history</small>}</td>)}<td className="lab-table-total"><Total stock={s}/></td></tr>)}</tbody></table></div>{!rows.length&&<p>No matching stocks.</p>}</section></>}</section>
}
