import {signalStatus} from './signalStatus.mjs'
import {SignalBadge} from './SignalBadge.jsx'
import {SignalStockDetail} from './SignalStockDetail.jsx'
import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import {SignalRadar} from './SignalLab.jsx'
import {rankSignals} from './signalRanking.mjs'
import './signal-overview.css'
const signalUrl=(ticker,axis=0)=>'/signal-lab/'+encodeURIComponent(ticker)+(axis?'?axis='+axis:'')
const selection=()=>{const ticker=/^\/signal-lab\/([A-Z0-9.\-]{1,12})\/?$/i.exec(location.pathname)?.[1]||new URLSearchParams(location.search).get('ticker');const axis=Number(new URLSearchParams(location.search).get('axis'));return ticker&&/^[A-Z0-9.\-]{1,12}$/i.test(ticker)?{ticker:ticker.toUpperCase(),axis:Number.isInteger(axis)&&axis>=0&&axis<5?axis:0}:null}
const number=v=>v==null?'—':Number(v.toFixed(1))
function Total({stock}){return <><strong>{number(stock.total)}</strong><small>{stock.available===5?' / 500':` points · ${stock.available}/5 available`}</small></>}
function Leaders({title,caption,rows,activity=false,onOpen,member=false}){return <section className="lab-leaders"><div className="section-head"><div><h2>{title}</h2><p className="muted">{caption}</p></div></div><div className="lab-leader-grid">{rows.slice(0,3).map((s,i)=><article className="panel lab-leader" key={s.ticker}><div className="section-head"><div><a className="lab-open-stock lab-tile-link" href={member?signalUrl(s.ticker):"#"} aria-label={`Open ${s.ticker} Signal Lab details`} onClick={e=>{if(!member){e.preventDefault();onOpen(s.ticker)}}}>${s.ticker}</a><small className="block muted">{s.name}</small></div><span className="signal-rank">0{i+1}</span></div><div className="lab-badged-radar"><SignalBadge candidate={s.candidate}/><SignalRadar axes={s.axes}/></div><div className="lab-card-score">{activity?<><strong>{number(s.activity)}</strong><small> / 100 X activity</small></>:<Total stock={s}/>}</div><small className="muted">{s.available<5?'Partial coverage · ':''}{s.stale?'Last saved view':'Latest saved view'}</small></article>)}</div>{!rows.length&&<p className="muted">Waiting for saved scores.</p>}</section>}
export function SignalOverview({member=false}){
 const [adminSelected,setSelected]=useState(null)
 const selected=member?selection():adminSelected
 const openStock=value=>{if(member)location.assign(signalUrl(value.ticker,value.axis));else setSelected(value)}
 const [data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[sort,setSort]=useState('total')
 useEffect(()=>{if(selected)return;let active=true;const load=()=>api(member?'/signal-lab/overview':'/admin/signal-lab-overview').then(d=>{if(active){setData(d);setError('')}}).catch(e=>{if(active)setError(e.message)});load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},120000);return()=>{active=false;clearInterval(timer)}},[selected,member])
 const ranked=rankSignals(data?.stocks),rows=(sort==='activity'?ranked.byActivity:ranked.rows).filter(s=>(s.ticker+' '+s.name).toLowerCase().includes(query.toLowerCase()))
 if(selected)return <SignalStockDetail member={member} key={selected.ticker} ticker={selected.ticker} initialAxis={selected.axis||0} onBack={()=>member?location.assign("/signal-lab"):setSelected(null)}/>
 return <section className="lab-overview"><span className="eyebrow">{member?'PRO · SIGNAL LAB':'ADMIN PREVIEW · SIGNAL LAB'}</span><h1>Find the names worth a closer look.</h1><p className="muted">Two ways to explore: the strongest X activity and the highest combined indicator scores.</p>{error&&<p className="error" role="alert">{error}</p>}{!data&&!error&&<p>Loading saved scores…</p>}{data&&<><Leaders title="Leading the conversation" caption="Top 3 by X activity" rows={ranked.byActivity} member={member} onOpen={ticker=>openStock({ticker})} activity/><Leaders title="Highest overall points" caption="Five indicators · up to 500 points" rows={ranked.byTotal} member={member} onOpen={ticker=>openStock({ticker})}/><p className="lab-coverage-note">Complete scores rank first. While history builds, partial scores are ordered by coverage, then available points. Missing indicators stay unavailable. The total combines the displayed scores; it is not a probability or a bullish/bearish direction.</p><section className="panel"><div className="section-head"><div><h2>Signal overview</h2><p className="muted">{ranked.rows.length} names with saved observations</p></div><div className="lab-filters"><input aria-label="Search Signal Lab stocks" placeholder="Ticker or company" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort Signal Lab" value={sort} onChange={e=>setSort(e.target.value)}><option value="total">Overall points</option><option value="activity">X activity</option></select></div></div><div className="table-scroll"><table className="lab-comparison"><colgroup><col className="lab-rank-col"/><col className="lab-stock-col"/><col className="lab-shape-col"/>{Array.from({length:5},(_,i)=><col key={i}/>)}<col className="lab-total-col"/></colgroup><thead><tr><th>#</th><th>Stock</th><th className="lab-shape-heading">Signal shape</th><th>Price</th><th>Volume</th><th>Options</th><th>X activity</th><th>Catalyst</th><th>Total</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.ticker} className="lab-clickable-row" onClick={e=>{if(!e.target.closest("button,a"))openStock({ticker:s.ticker})}}><td>{i+1}</td><td className="lab-stock-cell"><button className="lab-open-stock" onClick={()=>openStock({ticker:s.ticker})}>${s.ticker}</button><small className="lab-company-name muted" title={s.name}>{s.name}</small></td><td className="lab-table-radar"><SignalRadar axes={s.axes} compact/></td>{s.axes.map((a,axis)=><td key={a.name} title={a.reason}><button className="lab-axis-link" aria-label={`Open ${a.name} history for ${s.ticker}`} onClick={()=>openStock({ticker:s.ticker,axis})}>{number(a.score)}</button>{a.score==null&&<small className="block muted">{signalStatus(a)}</small>}</td>)}<td className="lab-table-total"><Total stock={s}/></td></tr>)}</tbody></table></div>{!rows.length&&<p>No matching stocks.</p>}</section></>}</section>
}
