import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import {dualTime} from './time.js'
import {tradingViewUrl,affiliateEnabled} from './tradingview.js'
import {TradingViewDisclosure} from './TradingView.jsx'
import './supply-chain.css'
import './trending-research.css'
function ResearchRow({row,index,onTicker,featured=false}){
 const [open,setOpen]=useState(false)
 return <article className={"research-ranking-row"+(featured?" research-featured-card":"")}><button className="research-ranking-summary" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span className="research-position">{index==null?'—':String(index+1).padStart(2,'0')}</span><span><strong>${row.ticker}</strong><small>{row.name}</small></span><span>{row.research[0].link_type==='sector_readthrough'&&<small className="tag">Sector read-through</small>}<strong>{row.research[0].summary}</strong><small>{row.research[0].report_date}{row.intraday_rank?` · Intraday #${row.intraday_rank}`:''}</small></span><span>{open?'Close −':'Read +'}</span></button>{open&&<div className="research-ranking-expanded">{row.research.map(r=><div key={r.id}>{r.firm&&<span className="tag">{r.firm}</span>}{r.link_type==='sector_readthrough'&&<p className="muted"><strong>Sector read-through</strong> · {r.link_reason}</p>}<p>{r.summary}</p>{r.catalysts?.length>0&&<p><strong>What to watch: </strong>{r.catalysts.join(' · ')}</p>}{r.risks?.length>0&&<p><strong>Risks: </strong>{r.risks.join(' · ')}</p>}</div>)}<footer className="research-actions"><button className="button primary" onClick={()=>onTicker(row.ticker)}>Open ${row.ticker} details ↗</button><a className="button primary" href={tradingViewUrl(row.ticker)} target="_blank" rel={affiliateEnabled?"sponsored nofollow noopener noreferrer":"noopener noreferrer"}>Open ${row.ticker} on TradingView ↗</a></footer><TradingViewDisclosure/></div>}</article>
}
export function TrendingResearch({refresh,onPlans,onTicker}){
 const [data,setData]=useState(null),[error,setError]=useState('')
 useEffect(()=>{let active=true;api('/trending-research').then(d=>{if(active){setData(d);setError('')}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[refresh])
 const ordered=data?[...data.rows,...data.other].slice(0,30):[], featured=ordered.slice(0,3), remaining=ordered.slice(3)
 return <section className="panel"><span className="eyebrow">THE CONVERSATION, WITH CONTEXT</span><h2>Trending Research <span className="premium-badge">Pro</span></h2><p className="muted">Today’s research, ordered by 24-hour Market pulse rank. Remaining spotlight places feature the newest available notes. Today follows New York time.</p>{error&&<p role="alert" className="error">{error}</p>}{!data&&!error&&<p role="status">Loading research…</p>}{data&&<><small className="muted">Checked · {dualTime(data.as_of)}</small>{featured.length>0&&<div className="research-featured-grid">{featured.map((r,i)=><ResearchRow key={r.ticker} row={r} index={i} onTicker={onTicker} featured/>)}{data.locked&&featured.length<3&&<article className="research-featured-locked" aria-label="More research with Premium"><span className="premium-badge">Premium</span><h3>More perspectives.</h3><p>Discover the full research selection.</p><button className="button primary" onClick={onPlans}>Upgrade your plan ↗</button></article>}</div>}{remaining.length>0&&<><h3 className="research-more-heading">More research</h3><p className="muted">Newest report dates first. Upload time breaks ties; market rank does not affect this list.</p><div className="research-ranking">{remaining.map((r,i)=><ResearchRow key={r.ticker} row={r} index={i+3} onTicker={onTicker}/>)}</div></>}{data.locked&&<section className="supply-paywall research-paywall"><div className="supply-fade-preview" aria-hidden="true">{[1,2,3].map(n=><div key={n}><i/><i/><i/></div>)}</div><div className="ranking-upgrade"><span className="premium-badge">Premium</span><h2>Unlock the full research overview.</h2><p>Your free preview includes two research previews. Upgrade to Premium to get the full Trending Research overview.</p><button className="button primary" onClick={onPlans}>Upgrade your plan ↗</button></div></section>}{!data.total&&!data.locked&&<p className="muted">Reviewed research will appear here once published.</p>}</>}</section>
}
