import React,{useEffect,useState} from 'react'
import {api} from './api.js'
import {dualTime} from './time.js'

export function UwPilot(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);setError('');try{setData(await api('/admin/uw-pilot'))}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{let active=true;api('/admin/uw-pilot').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 return <section className="panel"><div className="section-head"><div><span className="eyebrow">PRIVATE · OWNER ONLY</span><h2>Signal Lab · data connection</h2></div><button className="button" disabled={busy} onClick={load}>{busy?'Loading…':'Refresh status'}</button></div><p>Unusual Whales Basic evaluation. Saved observations only; refreshing this panel does not call UW.</p>{error&&<p className="error" role="alert">{error}</p>}{data&&<><div className="stats"><div className="stat"><div>API key</div><strong>{data.key_saved?'Saved':'Not connected'}</strong></div><div className="stat"><div>Private evaluation permission</div><strong>{data.evaluation_approved?'Confirmed':'Pending'}</strong></div><div className="stat"><div>Automatic collection</div><strong>{data.enabled?'Enabled':'Disabled'}</strong></div></div><p>Initial pilot: {data.tickers.join(', ')}. Each stock is checked every 10 minutes during weekday US regular hours. Scores remain unavailable until feed quality and baseline coverage are validated.</p><p className="muted">Provider net premium is an aggregate observation. It does not yet apply our proposed expiry and single-leg filters, and is not a trading signal.</p><p>Requests this UW quota day: {Math.max(data.usage?.reserved||0,data.usage?.provider_count||0).toLocaleString()} · local ceiling {data.local_daily_cap.toLocaleString()} · provider allowance {data.usage?.provider_limit?.toLocaleString()||'not yet verified'}</p>{data.last_run&&<p>Last worker: {dualTime(data.last_run.at)} · {data.last_run.state} · {data.last_run.completed} completed / {data.last_run.failed} failed</p>}{!data.rows.length?<p className="empty">No UW observations collected yet. The importer is prepared; account setup and a private API key are still needed.</p>:<div className="table-scroll"><table><thead><tr><th>Stock</th><th>Dataset</th><th>Status</th><th>Source time</th><th>Latest observation</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.ticker+r.kind}><td>${r.ticker}</td><td>{r.kind==='candles'?'10-minute price / volume':'Net options premium'}</td><td>{r.state}{r.error?' · '+r.error:''}</td><td>{r.data_at?dualTime(r.data_at):'Unavailable'}</td><td>{r.latest?(r.kind==='candles'?`Close $${r.latest.close} · ${r.latest.volume.toLocaleString()} shares`:`Net calls $${r.latest.net_call_premium.toLocaleString()} · net puts $${r.latest.net_put_premium.toLocaleString()}`):'No usable data'}</td></tr>)}</tbody></table></div>}</>}</section>
}
