import React,{useEffect,useRef,useState} from 'react'
import {api} from './api.js'
import {dualTime} from './time.js'
import './UwPilot.css'
import {SignalPanel} from './SignalPanel.jsx'

const names={NVDA:'NVIDIA',AMD:'Advanced Micro Devices',MU:'Micron Technology'}
const number=v=>v==null?'Unavailable':new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v)
const dollars=v=>v==null?'Unavailable':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v)
const percent=v=>v==null?'Unavailable':`${v>0?'+':''}${v.toFixed(2)}%`
function Chart({rows,field,label,bars=false}){
 if(rows.length<2)return <div className="uw-chart-empty">Waiting for enough observations to draw {label.toLowerCase()}.</div>
 const vals=rows.map(r=>r[field]??0),min=bars?Math.min(0,...vals):Math.min(...vals),max=Math.max(...vals),span=max-min||1
 const x=i=>12+i*576/(rows.length-1),y=v=>130-(v-min)/span*110
 return <><svg className="uw-chart" viewBox="0 0 600 150" role="img" aria-label={`${label}: ${rows.length} observations; minimum ${number(min)}, maximum ${number(max)}`}><line x1="12" x2="588" y1={y(bars?0:min)} y2={y(bars?0:min)} stroke="currentColor" opacity=".2"/>{bars?rows.map((r,i)=><rect key={r.at} x={x(i)-2} y={Math.min(y(vals[i]),y(0))} width={Math.max(2,Math.min(12,500/rows.length))} height={Math.max(1,Math.abs(y(vals[i])-y(0)))} fill={vals[i]>=0?'#c9ef83':'#d9a171'}/>):<polyline points={vals.map((v,i)=>`${x(i)},${y(v)}`).join(' ')} fill="none" stroke="#c9ef83" strokeWidth="3"/>}</svg><div className="uw-chart-range"><span>{dualTime(rows[0].at,{date:false})}</span><span>{dualTime(rows.at(-1).at,{date:false})}</span></div></>
}
function StockDetail({stock,records,panel,history,now,scoring}){
 const prices=stock.candles,latest=prices.at(-1),fresh=stock.price_fresh&&stock.flow_fresh
 return <section className="uw-detail"><div className="section-head"><div><span className="eyebrow">LIVE OBSERVATIONS · NO COMPOSITE SCORE</span><h2>${stock.ticker} <span className="muted">{names[stock.ticker]}</span></h2></div><span className="uw-status">{fresh?'Fresh observations':'Check freshness / coverage'}</span></div>
 <SignalPanel panel={panel} history={history} now={now} error={scoring?.state==='evaluation_error'}/><div className="uw-metrics"><div><small>Latest completed close</small><strong>{dollars(latest?.close)}</strong></div><div><small>Price change · 60 minutes</small><strong>{percent(stock.return_60m)}</strong></div><div><small>Shares · 30 minutes</small><strong>{number(stock.volume_30m)}</strong></div></div>
 <div className="uw-plots"><section><h3>Price · completed 10-minute candles</h3><p className="muted">{dualTime(stock.price_at)} · {stock.price_fresh?'fresh':'stale or missing'}</p><Chart rows={prices} field="close" label="Price"/></section><section><h3>Volume · shares per candle</h3><p className="muted">Raw participation; the same-time historical comparison is below.</p><Chart rows={prices} field="volume" label="Volume" bars/></section></div>
 <div className="uw-plots"><section><h3>Net calls · latest 60 minutes</h3><strong className="uw-value">{dollars(stock.net_calls_60m)}</strong><Chart rows={stock.flow} field="net_call_premium" label="Net call premium" bars/></section><section><h3>Net puts · latest 60 minutes</h3><strong className="uw-value">{dollars(stock.net_puts_60m)}</strong><Chart rows={stock.flow} field="net_put_premium" label="Net put premium" bars/></section></div>
 <p className="muted">Flow timestamp: {dualTime(stock.flow_at)} · {stock.flow_fresh?'fresh':'stale or missing'}. Bars show minute increments; totals require 60 consecutive minutes. Aggregate net calls / puts are not the filtered directional options score.</p>
 <div className="uw-plots"><section><span className="eyebrow">VOLUME BASELINE / EXPERIMENTAL</span><h3>Same time, previous 20 sessions</h3><strong className="uw-value">{stock.volume_baseline?.relative_volume==null?'Building baseline':`${stock.volume_baseline.relative_volume.toFixed(2)}x usual volume`}</strong><p>{stock.volume_baseline?.sessions||0} / 20 sessions with three matching candles. Median: {number(stock.volume_baseline?.median_shares)} shares.</p><p>Persistence: {stock.volume_baseline?.persistence==null?'unavailable':`${stock.volume_baseline.persistence} of 3 candles above their same-time median`}. Participation, not direction. {stock.price_fresh?'':'Current window is stale.'}</p></section><section><span className="eyebrow">FILTERED OPTIONS / EXPERIMENTAL</span><h3>Single-leg / 7-60 days to expiry</h3>{stock.filtered_options?<><strong className="uw-value">{stock.filtered_options.partial?'Partial sample / collection limit':'60-minute query completed'}</strong><p>{stock.filtered_options.accepted} classified / {stock.filtered_options.received} received. {stock.filtered_options.excluded} excluded before deduplication.</p><p>Estimated bullish premium: {dollars(stock.filtered_options.bull)}<br/>Estimated bearish premium: {dollars(stock.filtered_options.bear)}</p><p>Checked {dualTime(stock.filtered_options.at)}. Classification uses call/put and bid/ask side; ambiguous trades are excluded. Not an opening-position or unhedged-conviction claim. {stock.filtered_options.partial?'No directional score is calculated from this partial sample.':''}</p></>:<p>No usable filtered sample collected yet. Check collection evidence for errors.</p>}</section></div>
 <details><summary>Collection evidence & window checks</summary><p>Full 60-minute price window: {stock.price_window_complete?'yes':'no'} · full 30-minute volume window: {stock.volume_window_complete?'yes':'no'} · full 60-minute flow window: {stock.flow_window_complete?'yes':'no'}. Missing intervals stay unavailable. Older values remain visibly stale and are not treated as current.</p>{records.map(r=><p key={r.kind}>{({candles:'Price / volume',net_premium:'Net premium',history:'Historical volume',filtered_options:'Filtered options'})[r.kind]}: {r.state}{r.error?` (${r.error})`:''} · collected {dualTime(r.fetched_at)} · source {dualTime(r.data_at)} · {r.observations} observations.</p>)}</details>
 </section>
}
export function UwPilot(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('NVDA')
 const alive=useRef(false),inflight=useRef(false)
 async function load(){if(inflight.current)return;inflight.current=true;setBusy(true);try{const d=await api('/admin/uw-pilot');if(alive.current){setData(d);setError('')}}catch(e){if(alive.current)setError(e.message)}finally{inflight.current=false;if(alive.current)setBusy(false)}}
 useEffect(()=>{alive.current=true;load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},60000);return()=>{alive.current=false;clearInterval(timer)}},[])
 const chosen=data?.stocks?.find(s=>s.ticker===selected)
 return <section className="panel uw-lab"><div className="section-head"><div><span className="eyebrow">PRIVATE · OWNER ONLY</span><h2>Signal Lab</h2><p>Three stocks. Real observations. A clear view of what is ready.</p></div><button className="button" disabled={busy} onClick={load}>{busy?'Checking…':'Refresh observations'}</button></div>{error&&<p className="error" role="alert">{error} {data?'Showing the last successful response.':''}</p>}{data&&<>
 <p className="muted">Screen checked {dualTime(data.server_at)}. Reads saved data every minute while visible; UW collection runs every 10 minutes. {data.session_open?'Weekday regular-hours window is open.':'Outside the weekday regular-hours window.'} No extra UW requests from this page.</p>
 <div className="uw-stock-picker" role="group" aria-label="Choose pilot stock">{data.stocks?.map(s=><button key={s.ticker} className={`uw-stock ${s.ticker===selected?'selected':''}`} aria-pressed={s.ticker===selected} onClick={()=>setSelected(s.ticker)}><span className="eyebrow">${s.ticker} · {s.price_fresh?'PRICE FRESH':'PRICE PENDING / STALE'}</span><h3>{names[s.ticker]}</h3><strong>{dollars(s.candles.at(-1)?.close)}</strong><span>{percent(s.return_60m)} · 60-minute change</span></button>)}</div>
 {chosen&&<StockDetail stock={chosen} records={data.rows.filter(r=>r.ticker===selected)} panel={data.lab?.stocks?.find(s=>s.ticker===selected)} history={(data.lab?.history||[]).filter(r=>r.ticker===selected)} now={data.server_at} scoring={data.scoring}/>}
 <details className="uw-connection"><summary>Connection, request budget & all pilot stocks</summary><p>API key: {data.key_saved?'saved':'not connected'} · evaluation permission: {data.evaluation_approved?'confirmed':'pending'} · collection: {data.enabled?'enabled':'disabled'}</p><p>Requests this quota day: {number(Math.max(data.usage?.reserved||0,data.usage?.provider_count||0))} / local ceiling {number(data.local_daily_cap)} · provider allowance {number(data.usage?.provider_limit)}</p>{data.last_run&&<p>Last worker: {dualTime(data.last_run.at)} · {data.last_run.state} · {data.last_run.completed} completed / {data.last_run.failed} failed</p>}<p>{data.tickers.join(', ')}</p><div className="table-scroll"><table><thead><tr><th>Stock</th><th>Dataset</th><th>Status</th><th>Source time</th></tr></thead><tbody>{data.rows.map(r=><tr key={r.ticker+r.kind}><td>${r.ticker}</td><td>{r.kind}</td><td>{r.state}{r.error?` · ${r.error}`:''}</td><td>{dualTime(r.data_at)}</td></tr>)}</tbody></table></div></details>
 </>}</section>
}
